services:
  razvanvideo:
    build: .
    volumes:
      - .:/razvanvideo
      - ./staticfiles:/razvanvideo/staticfiles
      - ./media:/razvanvideo/media
      - ./templates:/razvanvideo/templates
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - razvanvideo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./staticfiles:/razvanvideo/staticfiles
      - ./media:/razvanvideo/media
      - ./templates:/razvanvideo/templates
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot
    ports:
      - "8080:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot

volumes:
  static_volume:
  media_volume:
