version: '3.8'

services:
  razvanvideo:
    build: .
    volumes:
      - .:/app
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - razvanvideo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    ports:
      - "80:80"
      - "443:443"
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/nginx/certbot/conf:/etc/letsencrypt
      - ./docker/nginx/certbot/www:/var/www/certbot

volumes:
  static_volume:
  media_volume:
